version: '3.9'

services:
  todo-list-app:
    build: .
    container_name: todo-list-app
    restart: unless-stopped
    ports:
      - "25000:8080"
      
    environment:
      - SERVER_PORT=8080
    dns:
      - 8.8.8.8
      - 1.1.1.1
